# Generated by Django 4.2.7 on 2023-12-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('text', models.CharField(max_length=1000)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
